# Generated by Django 4.1.3 on 2022-12-05 09:25

import uuid

import django.db.models.deletion
import django.utils.timezone
import django_jsonform.models.fields
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import text_classifier.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=120)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sbert_models', django_jsonform.models.fields.ArrayField(base_field=models.CharField(choices=[('distiluse-base-multilingual-cased-v1', 'distiluse-base-multilingual-cased-v1'), ('paraphrase-multilingual-MiniLM-L12-v2', 'paraphrase-multilingual-MiniLM-L12-v2'), ('distiluse-base-multilingual-cased-v2', 'distiluse-base-multilingual-cased-v2'), ('paraphrase-multilingual-mpnet-base-v2', 'paraphrase-multilingual-mpnet-base-v2')], max_length=120), size=None)),
                ('classifiers', django_jsonform.models.fields.ArrayField(base_field=models.CharField(choices=[('RandomForestClassifier', 'RandomForestClassifier'), ('GradientBoostingClassifier', 'GradientBoostingClassifier'), ('SVC', 'SVC'), ('KNeighborsClassifier', 'KNeighborsClassifier'), ('MLPClassifier', 'MLPClassifier')], max_length=120), size=None)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextSample',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('probability', models.FloatField(default=1)),
                ('correction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_samples', to='text_classifier.category')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_samples', to='text_classifier.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_classifier.category')),
                ('sample', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample', to='text_classifier.textsample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_classifier.textmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sentence_model', models.CharField(max_length=250)),
                ('stored', models.FileField(upload_to=text_classifier.models.classifier_path)),
                ('is_active', models.BooleanField()),
                ('trained_at', models.DateTimeField(blank=True)),
                ('score', models.JSONField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_classifier.textmodel')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_classifier.trainingprocess')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_classifier.textmodel'),
        ),
    ]
